### PR TITLE
Added support for dis/reconnecting gamepads

### PR DESCRIPTION
**Pull request by Suitecake**
Fix for #447, #448 

Tested on Windows 7, 64-bit with a 360 controller (no other gamepads to test it on, unfortunately)

Removed runtime quitting of joystick subsystem and ignoring of joystick events. This seemed to cause more problems than it was worth.

### CODE REVIEW

**Comment by Bertram25** [comment]
Hi @Suitecake Sorry for the slow answer, I was quite away from reliable network the few last days.

I'll review and test all that asap. :)

**Comment by Suitecake** [comment]
Ah sorry; I keep catching myself with the bracing conventions, but I missed it here. =p

No worries about the time off!

**Comment by Bertram25** [comment]
Works fine! :) I'll merge and fixed indentation/use of braces.

**Comment by Bertram25** [comment]
Ah, btw, please indent using 4 spaces, no tabs.

**Comment by Suitecake** [comment]
Agh, that's a huge pet peeve of mine too. I forgot to configure my IDE for it.

Thanks for your patience here! I'll be sure to review my changes re: the coding standards before I put together another PR.

**Comment by Bertram25** [comment]
> Thanks for your patience here! I'll be sure to review my changes re: the coding standards before I put together another PR.

Np, I know it can hard to deal with the IDE config, especially when on different projects.

**Pull request merged**
