### PR TITLE
Moving the particle system rendering into its own class.

### PR DESCRIPTION
**Pull request by authenticate**
Hi,

In the original implementation, I implemented the particle system rendering logic within the sprite class.  This was done primarily to get the new OpenGL code working as quickly as possible.

However, since then, I went back and moved the particle system rendering into its own class.  This change will not affect much from a functional level.  However, I think it makes the code base clearer and should make any changes or fixes to these systems in the future a little easier and less confusing.

Let me know if there are any problems or issues.

Thanks.

### CODE REVIEW

**Comment by Bertram25** [comment]
Hey @authenticate :D 

And Happy New Year if it's not said already. ;)

I must say that moving the particles in their own class was something I wondering about, so it's perfect you just did it. :D Many thanks for that.

I'll review the code asap.

As for me, I hope to finish and push my own work soon. ;) (Scripting refactoring and refactoring, again, eh.)

Best regards,

**Comment by Bertram25** [comment]
A few warnings in need to be fixed:
```shell
> ValyriaTear/src/engine/video/text.cpp: In member function ‘void vt_video::TextSupervisor::_RenderText(const uint16*, vt_video::FontProperties*, const vt_video::Color&)’:
ValyriaTear/src/engine/video/text.cpp:1085:5: warning: narrowing conversion of ‘font_width’ from ‘int’ to ‘float’ inside { } is ill-formed in C++11 [-Wnarrowing]
     };
     ^

ValyriaTear/src/engine/video/text.cpp: In member function ‘void vt_video::TextSupervisor::_RenderText(const uint16*, vt_video::FontProperties*, const vt_video::Color&, float, float, const vt_video::Color&)’:
ValyriaTear/src/engine/video/text.cpp:1224:5: warning: narrowing conversion of ‘font_width’ from ‘int’ to ‘float’ inside { } is ill-formed in C++11 [-Wnarrowing]
     };
     ^
```
Same for 'font_height' each time.

As for cppcheck, it reported this:
```travis
[src/engine/video/gl/gl_particle_system.h:50]: (warning) Member variable 'ParticleSystem::_number_of_indices' is not assigned a value in 'ParticleSystem::operator='

[src/engine/video/gl/gl_particle_system.h:50]: (warning) Member variable 'ParticleSystem::_vao' is not assigned a value in 'ParticleSystem::operator='

[src/engine/video/gl/gl_particle_system.h:50]: (warning) Member variable 'ParticleSystem::_vertex_position_buffer' is not assigned a value in 'ParticleSystem::operator='

[src/engine/video/gl/gl_particle_system.h:50]: (warning) Member variable 'ParticleSystem::_vertex_texture_coordinate_buffer' is not assigned a value in 'ParticleSystem::operator='

[src/engine/video/gl/gl_particle_system.h:50]: (warning) Member variable 'ParticleSystem::_vertex_color_buffer' is not assigned a value in 'ParticleSystem::operator='

[src/engine/video/gl/gl_particle_system.h:50]: (warning) Member variable 'ParticleSystem::_index_buffer' is not assigned a value in 'ParticleSystem::operator='

[src/engine/video/gl/gl_shader.h:40]: (warning) Member variable 'Shader::_shader' is not assigned a value in 'Shader::operator='

[src/engine/video/gl/gl_shader_program.h:49]: (warning) Member variable 'ShaderProgram::_program' is not assigned a value in 'ShaderProgram::operator='

[src/engine/video/gl/gl_shader_program.h:49]: (warning) Member variable 'ShaderProgram::_vertex_shader' is not assigned a value in 'ShaderProgram::operator='

[src/engine/video/gl/gl_shader_program.h:49]: (warning) Member variable 'ShaderProgram::_fragment_shader' is not assigned a value in 'ShaderProgram::operator='

[src/engine/video/gl/gl_sprite.h:47]: (warning) Member variable 'Sprite::_vao' is not assigned a value in 'Sprite::operator='

[src/engine/video/gl/gl_sprite.h:47]: (warning) Member variable 'Sprite::_vertex_position_buffer' is not assigned a value in 'Sprite::operator='

[src/engine/video/gl/gl_sprite.h:47]: (warning) Member variable 'Sprite::_vertex_texture_coordinate_buffer' is not assigned a value in 'Sprite::operator='

[src/engine/video/gl/gl_sprite.h:47]: (warning) Member variable 'Sprite::_vertex_color_buffer' is not assigned a value in 'Sprite::operator='

[src/engine/video/gl/gl_sprite.h:47]: (warning) Member variable 'Sprite::_index_buffer' is not assigned a value in 'Sprite::operator='
```

Mind having a look?

I'll take care of the other warnings. Apart from those points, it is working great. :)

**Comment by authenticate** [comment]
I pushed up a change to resolve the warnings.

I need to look into a solution to enable that specific warning in VS.  It seems to be the one warning that VS does not care about at this warning level that the other compilers do.  I seem to miss it on almost every group of commits. :)



The cppcheck warnings are a little more complicated.

Those warnings are referring to the hidden copy constructors and assignment operators.  For example,

 ```
private:
    Shader(const Shader&) {}
    Shader& operator=(const Shader&) { return *this; }
```

These are compile time guards against the following: 

```
vt_video::gl::Shader a(... some parameters ...);
vt_video::gl::Shader b(... some parameters ...);

// This is prohibited by design.
a = b;
```

These classes contain OpenGL resources.  In addition, they clean up these resources in their destructors.  So, if you wanted to copy these classes, you would have to manually copy the OpenGL resources as well.  However, I believe that is a bad practice and/or design.  You do not want to create and destroy a lot of OpenGL resources at run time.  The hidden copy constructors and assignment operators help to prevent this as well as ensure the OpenGL resources are properly released.

So, in my opinion, the code is correct.  However, the cppcheck warning is also a good warning.  Under normal circumstances, I would want it to emit that warning.

I will wait for your feedback before doing anything.

I have been thinking about the following options, none of which I really like:

1. Remove the offending code.
  * I think this is the worst option.  The code base is more error prone without the guards.
2. Stub out the code so it no longer emits the warning.
  * This is not a terrible option.  I think it would make the code a little messier; which is not the end of the world.  It might make someone maintaining the code in the future confused as to what it is actually doing.
3. Leave the code as is.
  * I do not like this option.  I think it clutters the cppcheck output making it more difficult to find actual problems.
4. Suppress the warning.
  * I do not like this option. The warning itself is valid and should be emitted.

Anyways, let me know what you think.

**Comment by Bertram25** [comment]
Hey @authenticate :)

Sorry to keep you waiting and thanks a lot for all the work on it.

About the hidden copy constructors, I now get the point to prevent triggering them by design and break compilation on purpose to permit debugging, which is sane. :)
I wasn't actually sure as even defined the operator= constructor with a proper return, but now I get it.

Now, to clearly show it is forbidden, I would add a comment and why not a throw_exception within function.
I will also have a look at suppressing the warning in cppcheck.

I can handle all that if you want as your code is more than fine, actually. :)

(I'll merge now.)

**Pull request merged**
