### PR TITLE
Fix some crashing bugs

### PR DESCRIPTION
**Pull request by endoalir**
These two changes prevent the program from crashing. A a patch to LuaBind prevents exceptions from being lost, and the other one prevents use of a dangling pointer.

### CODE REVIEW

**Comment by Bertram25** [comment]
Hi @endoalir 
Thanks for the catch! :dancer:  I'll also note down your other notes in a new issue so I don't forget to fix them as well.
Could you rebase your branch so that the commits are cleaned out of oldies, or do you prefer me to cherry pick what's interesting?

Best regards,

**Comment by akien-mga** [comment]
Is it not possible to achieve the same thing without patching luabind? Patching an external dependency can usually become problematic for downstream packagers who would try to build the game against their system's luabind, and might run into issues (e.g. on Debian).

Generally speaking it would be better to get the changes approved upstream directly. Luabind is not particularly actively developed though. This pending PR might be relevant btw: https://github.com/luabind/luabind/pull/26

**Comment by Bertram25** [comment]
> Is it not possible to achieve the same thing without patching luabind? Patching an external dependency can usually become problematic for downstream packagers who would try to build the game against their system's luabind, and might run into issues (e.g. on Debian).

You're completely right. I must say I didn't even start to watch for similar fixes in luabind. But, yeah, luabind definitely needs some love. Also, I already tried to make upstream react but nothing so far: https://github.com/luabind/luabind/issues/28

VT might have to drop Luabind one day, unfortunately, simply because of that, or find a better fork to follow maybe?

**Comment by Bertram25** [comment]
@endoalir @akien-mga has definitely a point while luabind upstream is definitely dead IMHO.

I've thus cherry-picked https://github.com/endoalir/ValyriaTear/commit/3fa7e1be9e52bb2691e98c2e2273dd897bc5ae14 into main master (Thanks for the catch!!)

And I definitely have to define the road toward the fix of the this issue and luabind which are probably related. I've thus opened issue #480 
I'll close this PR for now, but will definitely do something about calling the function in the constructor! :D

**Pull request closed without merging**
