### PR TITLE
A Test to Fix the Minimap Bug

### PR DESCRIPTION
**Pull request by authenticate**
This is a test commit to try and fix the minimap bug on Intel drivers.  I wouldn't actually merge it.

However, let me know if it fixes anything.

Thanks.

### CODE REVIEW

**Comment by Bertram25** [comment]
Simple enough. I guess you are reluctant to see it merged because of the direct gl call.

Anyway thanks a lot for all your help. :) I'll test asap.

**Comment by Bertram25** [comment]
I just tested it. It's working fine. :D

**Comment by authenticate** [comment]
I made some updates to the PR.

First, while some what off topic, I added a small commit to address some minor errors with the OpenGL diagnostics.  This should hopefully clean that up.

In addition, I updated the rendering API for the scissor rectangle.  I will admit the change is a little intrusive.  However, I think the change is for the better.

The scissor rectangle is a well-defined structure.  It exists in a certain coordinate space by definition.  In the original implementation, we were storing the scissors rectangle as part of the renderer's state.  However, we weren't quite storing a scissors rectangle.  The rectangle was being stored in an alternate coordinate space.  Then, every time we wanted to use it, it was converted back into the correct space prior to being passed into OpenGL.  This felt messy.

So, I attempted to clean things up and try to make the implementation more standard.

As a final note, I was unable to test the text box code which uses the scissor rectangle.  If the text box is in mode "VIDEO_TEXT_REVEAL", it uses the scissor rectangle.  However, I am not sure which part of the game uses this.

Let me know what you think.

**Comment by Bertram25** [comment]
> In addition, I updated the rendering API for the scissor rectangle. I will admit the change is a little intrusive. However, I think the change is for the better.

Np, I agree completely with the change. It looks cleaner and easier to follow now.

> As a final note, I was unable to test the text box code which uses the scissor rectangle. If the text box is in mode "VIDEO_TEXT_REVEAL", it uses the scissor rectangle. However, I am not sure which part of the game uses this.

This feature is, AFAIK, unused and was, at the time I retook the code, already unused and AFAIK non-functional. (Or maybe I broke it without noticing?). In any case, non of the game is using it.
If you feel like readding it, feel free to go while I don't want to put any pressure on you. :)
It might just be interesting to display some text that way on epic moments and such, but it's no priority.

I'll test asap and merge if everything goes fine. :)
Again, thanks a lot for all your help on that part. You can't imagine how I feel glad being helped about that. :D

**Comment by Bertram25** [comment]
Working fine, I merge.

**Pull request merged**
