### PR TITLE
Rush implementation

### PR DESCRIPTION
**Pull request by Suitecake**
Initial implementation of Battle Menu and Rush (#371)

### CODE REVIEW

**Comment by Suitecake** [comment]
Looks like C++11 isn't enabled yet on Travis-CI

**Comment by Bertram25** [comment]
> Looks like C++11 isn't enabled yet on Travis-CI

Let's enable it. :) I'll add this need in #464

**Comment by Bertram25** [comment]
The code looks clean. Congrats :)

I'll test asap.

**Comment by Bertram25** [comment]
Hey @Suitecake :)

I've worked on adding c++11 support in travis and throughout the project code. :) You'll have to rebase. ;)

Also, I've tested it. The menu is displayed fine when pushing the menu key, but there are a few things:
- First one, the battle update is paused (it shouldn't IMO).
- Also, it made so that the rush menu doesn't *seem* to react to the the confirm key to the user, only to the cancel one while it isn't true.
It seems to me you simply enabling the `_rush_active` boolean and then setting the actions in the battle update mode. This is IMHO a bit lazy. I would create a dedicated function in the battle mode class for that and make the confirming in the 'rush' window call this function and close the window back to the standard mode immediately.
I would also reduce the window size, place it above the standard command menu, and not use Uppercased characters only for the 'RUSH' text (e.g.: 'Rush' instead of 'RUSH').

Could you do that?

Thanks to your feature, we will then be able to add more options, like Flee.

**Comment by Suitecake** [comment]
Time to learn how rebasing works =p

I'll fix those issues.

**Comment by Suitecake** [comment]
Still learning how PRs work. I decided to reset my master branch (which this PR was based on) and continue work in a feature branch, not realizing that would close the PR.

I'll open a second one when I have these issues sorted.

**Comment by Bertram25** [comment]
@SuiteCake np, :) Don't hesitate to even create a new one if it's easier for you.

**Pull request closed without merging**
