### PR TITLE
Fix item equipping, more dangling pointers, and access violations

### PR DESCRIPTION
**Pull request by endoalir**
The code changes in these commits fix memory access violations and dangling pointers that cause the program to crash. In particular, these changes make equipping and unequipping items work much better.

### CODE REVIEW

**Comment by Bertram25** [comment]
@endoalir To get a clearer view you changes (which are interesting to merge!), could you rebase?
`git pull --rebase`
This will clear up old patches.

**Comment by Bertram25** [comment]
I'll push the relevant commits now + small indent fixes :)

I do think you should try to get rid of the old patches by making at hard reset at your branch and repull or delete it and refork it. :)

Thanks again for the small fixes!

**Comment by Bertram25** [comment]
It's done. The interesting commits were merged. Thanks!
Once again, I do think you should maybe refork to clean up old patches.

**Comment by endoalir** [comment]
Thanks for the advice. I did refork.

**Comment by Bertram25** [comment]
Closing this one, as corresponding commits have been merged.

**Pull request closed without merging**
